//@version=5 
indicator(shorttitle="sq 5BB", title="5 BBand and jam moments", overlay=true) 
 
tfm1=input.timeframe(defval="240", title="1. Select BBand Candle Duration") 
 
length = input.int(20, minval=2) 
src = input(close, title="Source") 
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev") 
basis = ta.sma(src, length) 
dev = mult * ta.stdev(src, length) 
upper = basis + dev 
lower = basis - dev 
 
upper1=request.security(syminfo.tickerid,tfm1,upper,gaps=barmerge.gaps_off, lookahead = barmerge.lookahead_on) 
lower1=request.security(syminfo.tickerid,tfm1,lower,gaps=barmerge.gaps_off, lookahead = barmerge.lookahead_on) 
 
sq1=(upper1-lower1)<ta.sma(upper1-lower1,10) and ta.sma(upper1-lower1,10)<ta.sma(upper1-lower1,20) and (upper1-lower1) == ta.lowest((upper1-lower1), 20) 
 
u1=plot(upper1,title="1. BBand Upper Line Color", color=color.gray, linewidth = 1, display = display.none) 
l1=plot(lower1,title="1. BBand Lower Line Color", color=color.gray, linewidth = 1, display = display.none) 
 
Cond_Color1=sq1 ? color.new(color.blue,60) : color.new(color.gray,93) 
 
fill(u1,l1, title="1. BBand fill Color", color=Cond_Color1, fillgaps = false)
